name: MUDHENWATER
favicon: null
layout_spectrum: 0.02656
typography_spectrum: 0.40934
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f6f8'
    - '#c2bebf'
    - '#0f100c'
    - '#41392f'
    - '#af7943'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
