name: MUDHENWATER
favicon: null
layout_spectrum: 0.02656
typography_spectrum: 0.006889299489557743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0706'
    - '#ffffff'
    - '#726a56'
    - '#ccb4a4'
    - '#ef8375'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
